# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Capybasics Blog
email: capybasics@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This blog was created by André Silva Gusmão to compile and share his experiences while studying IT-related topics, primarily Software Development and DevOps. 
  The posts in this blog serve as personal study reference material for André, while also sharing it with the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: andre-silva-gusmao
youtube_channel: '@Capybasics'
website_url: "https://capybasics.com/"
github_username:  andresilvagusmao

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Site Settings
author: "André Silva Gusmão"

# Build Settings
markdown: kramdown  # The markdown processor to use

# Permalinks
permalink: /:categories/:year/:month/:day/:title/  # Customize the URL structure of posts

# Social Links (optional)
# twitter_username: mytwitterhandle  # Add your social media links
# github_username: mygithubhandle

# Plugins (optional)
# plugins:
#   - jekyll-feed  # RSS feed generation plugin
#   - jekyll-seo-tag  # SEO optimization plugin

# Custom Variables (optional)
show_excerpts: true  # Example custom variable to control showing post excerpts
google_analytics: UA-XXXXXXXX-X  # Google Analytics tracking ID
